# Generated by Django 5.2.1 on 2025-06-06 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TD', 'Tarjeta Débito'), ('TC', 'Tarjeta Crédito'), ('TR', 'Transferencia')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.CharField(max_length=50, unique=True)),
                ('nombre_articulo', models.CharField(choices=[('MARTILLO', 'Martillo'), ('DESTORNILLADOR', 'Destornillador'), ('TUERCA', 'Tuerca'), ('CLAVO', 'Clavo')], max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('comentarios', models.TextField(blank=True)),
                ('contacto2', models.CharField(blank=True, max_length=100)),
                ('proveedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_extra', to='myapp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_factura', models.CharField(choices=[('A', 'Factura A'), ('B', 'Factura B'), ('C', 'Factura C')], max_length=1)),
                ('punto_venta', models.IntegerField()),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exito', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('cae', models.CharField(blank=True, max_length=14, null=True)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.venta')),
            ],
        ),
    ]
