# Generated by Django 5.2.1 on 2025-06-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250606_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='punto_venta',
        ),
    ]
